### ISSUE TITLE
Cannot start new hyperapp

### ISSUE THREAD

**Issue by scheung38** [okwolf/create-hyperapp#2]
Showing just a blank page:

Manifest: Line: 1, column: 1, Syntax error.

package.json:

{
  "name": "my-hyperapp",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "hyperapp": "^2.0.4"
  },
  "devDependencies": {
    "hyperapp-scripts": "^0.3.0"
  },
  "scripts": {
    "start": "hyperapp-scripts start",
    "build": "hyperapp-scripts build",
    "test": "hyperapp-scripts test"
  },
  "eslintConfig": {
    "extends": "react-app",
    "rules": {
      "react/react-in-jsx-scope": "off",
      "no-unused-vars": [
        "warn",
        {
          "varsIgnorePattern": "^h$"
        }
      ]
    }
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by okwolf** [comment]
I believe the template needs to be updated for Hyperapp 2.

**Comment by okwolf** [comment]
Try again with the new version.

**Comment by okwolf** [comment]
Updated again today and should be working again with latest Hyperapp.
